name: final_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.9.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  image: ^3.0.2
  tflite_flutter: ^0.9.0
  google_ml_kit: ^0.13.0
  camera: ^0.9.4+19
  path_provider: ^2.0.9
  quiver: ^3.2.1
  sqflite: ^2.0.2
  path: ^1.8.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/others/
