name: final_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  camera: ^0.10.5+4
  cloud_firestore: ^4.9.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  google_mlkit_face_detection: ^0.8.0
  image: ^3.0.2
  path: ^1.8.0
  path_provider: ^2.0.9
  quiver: ^3.2.1
  sliding_up_panel2: ^3.3.0+1
  sqflite: ^2.0.2
  tflite_flutter: ^0.10.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/mobilefacenet.tflite
