// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo3RYkfaPAriBqoJlincpcAMyPFWzqurU',
    appId: '1:882607693559:web:e30d72d2b93ba115973df2',
    messagingSenderId: '882607693559',
    projectId: 'e-l34rn1ng-4pp5',
    authDomain: 'e-l34rn1ng-4pp5.firebaseapp.com',
    storageBucket: 'e-l34rn1ng-4pp5.appspot.com',
    measurementId: 'G-Q4B5GPW451',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASfR_WW7ud6LM40EXf0mM7yTgMmz5qkZE',
    appId: '1:882607693559:android:8244faae622e786f973df2',
    messagingSenderId: '882607693559',
    projectId: 'e-l34rn1ng-4pp5',
    storageBucket: 'e-l34rn1ng-4pp5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcaKoGB4WZlL6Ox2sIeVAU4zcKxL9hcUs',
    appId: '1:882607693559:ios:d698bec9e3dafd9a973df2',
    messagingSenderId: '882607693559',
    projectId: 'e-l34rn1ng-4pp5',
    storageBucket: 'e-l34rn1ng-4pp5.appspot.com',
    iosClientId: '882607693559-hhlb02ivqhlnlfbeetehgi768ick3hbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcaKoGB4WZlL6Ox2sIeVAU4zcKxL9hcUs',
    appId: '1:882607693559:ios:c9e61ea3fa57793d973df2',
    messagingSenderId: '882607693559',
    projectId: 'e-l34rn1ng-4pp5',
    storageBucket: 'e-l34rn1ng-4pp5.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
